Portfolio: mobile menu
AlexisJW/set-up-myFirst-mobile pull request #13
Opened 2022-12-19 20:16 UTC by AlexisJW

- When the user clicks (or taps) the hamburger button, the mobile menu appears.

-  When the user clicks (or taps) the close (X) button, the mobile menu disappears.

- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.

-  When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed.

2022-12-19 21:38 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @AlexisJW 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-19 21:38 UTC, tresorsawasawa commented on StyleSheet.css
> +}
- [ ] Kindly make sure your mobile menu design sticks as much as possible to the one from the Figma template. I suggest you improve your `blur effect`, `fonts on the text`, `spacing around and between elements`,... You can check all details from Figma to improve your design

| Figma design | Your Design |
| ------------------- | ------------------- |
| ![Screenshot from 2022-12-19 22-38-18](https://user-images.githubusercontent.com/83042742/208527401-87b55d73-e767-4ba1-ac2b-95e6fa6fd76d.png) | ![Screenshot from 2022-12-19 23-30-05](https://user-images.githubusercontent.com/83042742/208528088-331647fb-42c6-4ee9-900c-156b3f003e20.png) |

2022-12-19 21:38 UTC, tresorsawasawa commented on StyleSheet.css
> +  backdrop-filter: blur(20px);
- [ ] To match the Figma design, kindly make sure one party of the mobile menu design can not be visible before clicking the `hamburger` menu. Try to update your design and stick as much as possible to the expected design.
![Screenshot from 2022-12-19 22-34-52](https://user-images.githubusercontent.com/83042742/208528850-dabc0b0f-dfcf-4f40-aa8c-729676ba812d.png)

2022-12-20 02:38 UTC, Reem-lab approved these changes
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- Followed GitHub flow ✅
- Descriptivr PR ✅
- Great working on the menu functionality🔥🚀🎉
- Professional README ✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 15:45 UTC, merged